/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) Siemens AG, 2024
 */

#include <sysinfo.h>

enum sysinfo_id_iot2050 {
	BOARD_MLFB		= SYSINFO_ID_SMBIOS_SYSTEM_VERSION,
	BOARD_SERIAL		= SYSINFO_ID_SMBIOS_SYSTEM_SERIAL,
	BOARD_UUID		= SYSINFO_ID_SMBIOS_SYSTEM_UUID,
	BOARD_A5E		= SYSINFO_ID_SMBIOS_BASEBOARD_PRODUCT,
	BOARD_NAME		= SYSINFO_ID_SMBIOS_BASEBOARD_VERSION,
	BOARD_SEBOOT_VER	= SYSINFO_ID_USER + 0,
	BOARD_MAC_ADDR_CNT	= SYSINFO_ID_USER + 1,
	BOARD_MAC_ADDR_1	= SYSINFO_ID_USER + 2,
	BOARD_MAC_ADDR_START	= BOARD_MAC_ADDR_1,
	BOARD_MAC_ADDR_2	= SYSINFO_ID_USER + 3,
	BOARD_MAC_ADDR_3	= SYSINFO_ID_USER + 4,
	BOARD_MAC_ADDR_4	= SYSINFO_ID_USER + 5,
	BOARD_MAC_ADDR_5	= SYSINFO_ID_USER + 6,
	BOARD_MAC_ADDR_6	= SYSINFO_ID_USER + 7,
	BOARD_MAC_ADDR_7	= SYSINFO_ID_USER + 8,
	BOARD_MAC_ADDR_8	= SYSINFO_ID_USER + 9,
	BOARD_DDR_SIZE		= SYSINFO_ID_USER + 10,
};
